version: '2'

services: 
    node-app:
        image: my-node-tsc
        build: .
        ports: 
            - 3000:3000
        links:
            - redisdb
            - mongodb

    mongodb:
        image: mongo
        ports: 
            - 27017:27017
        environment: 
            - ME_CONFIG_MONGODB_AUTH_DATABASE=flash
        volumes: 
            - data:/data/db

    redisdb:
        image: redis
        ports: 
            - 6379:6379

volumes: 
    data: